[package]
name = "ash_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
ash = "0.38.0"
ash-window = "0.13.0"
gltf = "1.4.1"
image = "0.25.5"
nalgebra = "0.33.2"
shaderc = "0.8.3"
winit = { version = "0.30.5", features = ["rwh_06"] }
